# name: "Create a simple Rmarkdown website"
# navbar:
#   left:
#     - text: "Home"
#       href: index.html
#     - text: "Getting Started"
#       menu:
#         - text: "Create a Project"
#           href: project.html
#         - text: "Set Build Options"
#           href: build.html
#         - text: "Create a _site.yml"
#           href: create_yml.html
#     - text: "Add Features"
#       menu:
#         - text: "Tables and Plots"
#           href: tables_plots.html
#         - text: "Include Images"
#           href: images.html
#         - text: "Embed a webpage"
#           href: embed.html
#     - text: "Publish and Update"
#       menu:
#         - text: "Publishing"
#           href: publishing.html
#         - text: "Updating"
#           href: updating.html
# output_dir: "."


    name: Generate xml sitemap

on:
  push:
    branches: [ main ]

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Generate a sitemap

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Generate the sitemap
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://areeba-droid.github.io/Areeba-Ali/

    - name: Commit and push
      run: |
        if [[ `git status --porcelain sitemap.xml` ]]; then
          git config --global user.name 'github-actions'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add sitemap.xml
          git commit -m "Automated sitemap update" sitemap.xml
          git push
# fi
